steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t southamerica-east1-docker.pkg.dev/microservices-nats-nest/images-register-docker/products-ms-prod -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL_BUILD=$$DATABASE_URL .
  secretEnv: ['ORDERS_DATABASE_URL_BUILD']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'southamerica-east1-docker.pkg.dev/microservices-nats-nest/images-register-docker/orders-ms-prod',
    ]

availableSecrets:
  secretManager: 
  - versionName: projects/62922609665/secrets/ORDERS_DATABASE_URL_BUILD/versions/1
    env: 'DATABASE_URL'
options:
  logging: CLOUD_LOGGING_ONLY
  # second try